export default {
  GET_POPULAR_MOVIES: 'GET_POPULAR_MOVIES',
	GET_POPULAR_SERIES: 'GET_POPULAR_SERIES',
	// SELECCIONAR_PARTICIPANTE: 'SELECCIONAR_PARTICIPANTE',
  // DESELECCIONAR_PARTICIPANTE: 'DESELECCIONAR_PARTICIPANTE',
	// REMOVER_PARTICIPANTE: 'REMOVER_PARTICIPANTE',
}
